name: muslimapps
description: Market


version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  # source_gen: ^0.9.4+7
  flutter:
    sdk: flutter
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  hydrated_bloc: ^3.0.0
  equatable: ^1.1.1
  flutter_screenutil: ^1.0.2
  font_awesome_flutter: ^8.7.0
  flutter_calendar_carousel: ^1.4.11
  date_format: ^1.0.8
  retrofit: ^1.3.1+1
  dio: ^3.0.9
  shimmer: ^1.1.0
  permission_handler: ^4.3.0
  geolocator: ^5.3.0
  google_maps_flutter: ^0.5.24+1
  flutter_rating_bar: ^3.0.1+1
  intl: ^0.16.1
  url_launcher: ^5.4.2
  flutter_compass: ^0.3.6
  firebase_auth: ^0.15.5+2
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  google_sign_in: ^4.1.4
  libcalendar: ^0.2.0
 # flutter_facebook_login: ^3.0.0
  flutter_html: ^0.11.1
  #workmanager: ^0.2.1
  #logger: ^0.8.3

  # logger: ^0.8.3
  #next (division)
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
 # source_gen: ^0.9.4+7
  retrofit_generator: ^1.3.1+4
  hive_generator: ^0.7.0+2
  build_runner:
  json_annotation: ^3.0.1
 # json_serializable: ^3.2.5
  flutter_test:
    sdk: flutter
  progress_dialog: ^1.2.1



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
